name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature
      placeholder: "Add ability to search users by Discord username"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently it's difficult to find users when you only know their Discord name..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "Add a search field that accepts Discord usernames and filters the user list..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocks important tasks
        - Critical - Required for basic functionality
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - User Management
        - Authentication
        - TrueSkill/MMR System
        - UI/Frontend
        - API/Backend
        - Database
        - Deployment/Infrastructure
        - Other

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Other ways this problem could be solved

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, related issues, or other helpful information