-- USL-Specific Tables (Temporary Migration)
-- These tables mirror the Google Sheets CSV structure exactly
-- Will be migrated to multi-guild schema later

-- USL Users table - matches League Management - User.csv exactly
CREATE TABLE usl_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    discord_id TEXT UNIQUE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    banned BOOLEAN NOT NULL DEFAULT false,
    mmr INTEGER NOT NULL DEFAULT 0,
    trueskill_mu DECIMAL(10,6) NOT NULL DEFAULT 1000.0,
    trueskill_sigma DECIMAL(10,6) NOT NULL DEFAULT 8.333333,
    trueskill_last_updated DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- USL User Trackers table - matches League Management - UserTracker.csv exactly  
CREATE TABLE usl_user_trackers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discord_id TEXT NOT NULL,
    url TEXT NOT NULL,
    ones_current_season_peak INTEGER DEFAULT 0,
    ones_previous_season_peak INTEGER DEFAULT 0,
    ones_all_time_peak INTEGER DEFAULT 0,
    ones_current_season_games_played INTEGER DEFAULT 0,
    ones_previous_season_games_played INTEGER DEFAULT 0,
    twos_current_season_peak INTEGER DEFAULT 0,
    twos_previous_season_peak INTEGER DEFAULT 0,
    twos_all_time_peak INTEGER DEFAULT 0,
    twos_current_season_games_played INTEGER DEFAULT 0,
    twos_previous_season_games_played INTEGER DEFAULT 0,
    threes_current_season_peak INTEGER DEFAULT 0,
    threes_previous_season_peak INTEGER DEFAULT 0,
    threes_all_time_peak INTEGER DEFAULT 0,
    threes_current_season_games_played INTEGER DEFAULT 0,
    threes_previous_season_games_played INTEGER DEFAULT 0,
    last_updated DATE,
    valid BOOLEAN NOT NULL DEFAULT true,
    mmr INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    -- Foreign key to USL users
    CONSTRAINT fk_usl_user_trackers_discord_id 
        FOREIGN KEY (discord_id) REFERENCES usl_users(discord_id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX idx_usl_users_discord_id ON usl_users(discord_id);
CREATE INDEX idx_usl_users_active ON usl_users(active) WHERE active = true;
CREATE INDEX idx_usl_users_mmr ON usl_users(mmr DESC);
CREATE INDEX idx_usl_users_trueskill_mu ON usl_users(trueskill_mu DESC);

CREATE INDEX idx_usl_user_trackers_discord_id ON usl_user_trackers(discord_id);
CREATE INDEX idx_usl_user_trackers_valid ON usl_user_trackers(valid) WHERE valid = true;
CREATE INDEX idx_usl_user_trackers_mmr ON usl_user_trackers(mmr DESC);
CREATE INDEX idx_usl_user_trackers_last_updated ON usl_user_trackers(last_updated);

-- Enable RLS (Row Level Security) - open for now since USL-only
ALTER TABLE usl_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE usl_user_trackers ENABLE ROW LEVEL SECURITY;

-- Simple policies - allow all for authenticated users (USL-only system)
CREATE POLICY "USL users are viewable by authenticated users" ON usl_users
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "USL users can be inserted by authenticated users" ON usl_users
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "USL users can be updated by authenticated users" ON usl_users
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "USL user trackers are viewable by authenticated users" ON usl_user_trackers
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "USL user trackers can be inserted by authenticated users" ON usl_user_trackers
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "USL user trackers can be updated by authenticated users" ON usl_user_trackers
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Triggers for updated_at timestamps
CREATE TRIGGER usl_users_updated_at
    BEFORE UPDATE ON usl_users
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER usl_user_trackers_updated_at
    BEFORE UPDATE ON usl_user_trackers
    FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- Comments for clarity
COMMENT ON TABLE usl_users IS 'USL-specific users table (temporary migration) - mirrors Google Sheets User.csv exactly';
COMMENT ON TABLE usl_user_trackers IS 'USL-specific trackers table (temporary migration) - mirrors Google Sheets UserTracker.csv exactly';